
TAG_HANDSET_INTERACT_DISTANCE = 3;
TAG_HANDSET_MAX_CABLE_DISTANCE = 4.5;
TAG_HANDSET_NEARBY_SCAN_RADIUS = 5;
TAG_HANDSET_SYNC_INTERVAL = 0.25;
TAG_HANDSET_MODEL = "z\tfar\addons\external_intercom\data\TFAR_handset.p3d";
TAG_HANDSET_ROPE_TYPE = "TFAR_RopeSmallWire";
